spring.datasource.jdbcUrl=jdbc:mysql://127.0.0.1:3306/dualdbtest?SslMode=none&autoReconnect=true&failOverReadOnly=false&maxReconnects=3
spring.datasource.username=root
spring.datasource.password=Pas$w0rd
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.hibernate.ddl-auto=update

spring.datasource-two.jdbcUrl=jdbc:postgresql://localhost:5432/dualdbtest?useUnicode=yes&characterEncoding=UTF-8
spring.datasource-two.username=postgres
spring.datasource-two.password=Pas$w0rd
spring.datasource-two.driverClassName=org.postgresql.Driver
#spring.datasource-two.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource-two.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource-two.hibernate.ddl-auto=update

flyway.enabled=false
spring.jpa.show-sql=true
